# Generated by Django 2.2.1 on 2019-05-04 00:40

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddny_braintree', '0015_remove_braintreetransaction_paypal_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braintreetransaction',
            name='status',
            field=model_utils.fields.StatusField(db_index=True, default='', max_length=100, no_check_for_status=True, verbose_name='Status'),
        ),
    ]
