# Generated by Django 2.2.1 on 2019-05-04 00:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0018_auto_20180715_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='other_price',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Other Price'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Total Price (for gas or equipment)'),
        ),
    ]
