# Generated by Django 2.2.1 on 2019-05-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0020_auto_20190504_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='other_cost',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='other_price',
        ),
    ]
