# Generated by Django 2.2.1 on 2019-05-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0021_auto_20190505_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='DEPRECATED_equipment_cost',
        ),
        migrations.RemoveField(
            model_name='fill',
            name='DEPRECATED_equipment_price',
        ),
    ]
