# Generated by Django 2.2.1 on 2019-05-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0022_auto_20190505_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='gas_price',
        ),
        migrations.AlterField(
            model_name='fill',
            name='equipment_price_proportional',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Equipment Price (per cubic foot)'),
        ),
    ]
