# Generated by Django 2.2.1 on 2019-05-05 04:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0023_auto_20190505_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='equipment_cost_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), editable=False, max_digits=20, verbose_name='Fixed Equipment Cost'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='equipment_cost_proportional',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), editable=False, max_digits=20, verbose_name='Proportional Equipment Cost'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='equipment_price_proportional',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Equipment Price'),
        ),
    ]
