# Generated by Django 2.2.1 on 2019-05-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0026_auto_20190505_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='equipment_price_proportional',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Equipment Price'),
        ),
    ]
