# Generated by Django 2.2.1 on 2019-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0027_auto_20190505_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='doubles_code',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Doubles code'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='tank_code',
            field=models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='Tank Code'),
        ),
    ]
