# Generated by Django 2.2.1 on 2019-05-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0028_auto_20190505_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fill',
            old_name='doubles_code',
            new_name='equipment_surcharge_key',
        ),
    ]
