# Generated by Django 2.2.20 on 2021-06-01 01:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillstation', '0030_auto_20190505_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total Price'),
        ),
    ]
