# Generated by Django 2.2.10 on 2020-05-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddny_calendar', '0006_auto_20160603_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
