# Generated by Django 2.2.1 on 2019-05-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20160825_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consenta',
            options={'verbose_name': 'Consent v1.1', 'verbose_name_plural': 'Consents v1.1'},
        ),
    ]
