# Generated by Django 2.2.1 on 2019-05-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20190504_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consenta',
            options={'ordering': ('-member_signature_date',), 'verbose_name': 'Consent v1.1', 'verbose_name_plural': 'Consents v1.1'},
        ),
    ]
