# Generated by Django 2.2.1 on 2019-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0011_auto_20180714_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='inspector_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vip',
            name='inspector_psi_number',
            field=models.CharField(max_length=30),
        ),
    ]
