# Generated by Django 2.2.1 on 2019-05-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0012_auto_20190511_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='inspector_psi_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
