# Generated by Django 2.2.10 on 2020-05-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0013_auto_20190511_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
