# Generated by Django 2.2.20 on 2021-06-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0015_auto_20200510_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='material',
            field=models.CharField(choices=[('Aluminum', 'Aluminum'), ('Steel', 'Steel'), ('FRP', 'FRP'), ('Composite', 'Composite')], default='Aluminum', max_length=9),
        ),
        migrations.AlterField(
            model_name='vip',
            name='tank_material',
            field=models.CharField(choices=[('Aluminum', 'Aluminum'), ('Steel', 'Steel'), ('FRP', 'FRP'), ('Composite', 'Composite')], default='Aluminum', max_length=9),
        ),
    ]
